### ISSUE TITLE
Sign In/Out button doesn’t change when user signs out

### ISSUE THREAD

**Issue by mtliendo** [mtliendo/focusOtter#10]

**Comment by mojiwa** [comment]
Hi there.
I have an idea to fix this bug, but when I try to run the dev build, I'm getting an error 
` make sure that './src/aws-exports' is installed`

I'm guessing that's because aws-exports.js is in the .gitignore. 
Is there a way to generate this file correctly? I'm assuming there's sensitive data in there. Do you have a dev version of this file?

Alternatively, I can just post my idea for a fix here.

Thanks.

**Comment by mtliendo** [comment]
Thanks so much for hopping in! You're correct, the way AmplifyJS projects work is that they create the `aws-exports.js` file which contains the secrets. There's isn't a way to create a stubbed version of it, but if you already have an AWS account and have the AWS cli installed, Amplify can get setup in a minute or so by [following this video](https://youtu.be/fWbM5DLh25U).

Apologies for the barrier to entry. Otherwise, I'd be happy to take a look at your solution 😃

**Comment by mojiwa** [comment]
> Thanks so much for hopping in! You're correct, the way AmplifyJS projects work is that they create the `aws-exports.js` file which contains the secrets. There's isn't a way to create a stubbed version of it, but if you already have an AWS account and have the AWS cli installed, Amplify can get setup in a minute or so by [following this video](https://youtu.be/fWbM5DLh25U).
> 
> Apologies for the barrier to entry. Otherwise, I'd be happy to take a look at your solution 😃

Hi. Was hoping to get this PR looked at for Hactober if possible. Thanks.

**Comment by mtliendo** [comment]
fixed in #20
